name: CotSLMain
version: '${project.version}'
main: me.wisemann64.soulland.SoulLand
api-version: 1.16
authors: [ WiseMann64 ]
website: https://github.com/WiseMann64
commands:
  test:
    description: test command
  item:
    description: get item
  mob:
    description: mob generator
  sltp:
    description: teleport ngab