package me.wisemann64.soulland.gameplay.objects;

public enum ActionTypes {
    SHOUT, SET_OBJECTIVE, TELEPORT, FILL_BLOCK, PLAY_DIALOGUE, PLAY_SEQUENCE, ADD_TRIGGER,
    SPAWN_MOB, DESPAWN_MOB, MOVE_MOB, TELEPORT_MOB,
    SPAWN_MODEL, DESPAWN_MODEL, MOVE_MODEL, TELEPORT_MODEL
}
